[Menu] 메뉴 등록 및 조회 기능 추가 #27
HeeHeePresso/Backend pull request #28
Opened 2024-03-10 15:11 UTC by kkkmj

### 개발 사항
- 메뉴 등록 api 추가
- 메뉴 조회 api 추가
- 메뉴 상태 수정 api 추가

+kotest 사용으로 인한 dependency 추가

### 리뷰 포인트
**참고사항**
1. 메뉴 수정의 경우 화면이 먼저 or 어떻게 수정하는 것이 좋을지 고민 해봐야 될 것 같아서 상태 수정만 만들었습니다.
2. 우선 개발 후 코드리뷰를 통해 개선하기 위해 pr 올렸습니다. (깊은 생각을 하지 않았다는 뜻...)
3. 영양정보의 경우 정확히 하고 추가하고 싶어 추가하지 않았습니다.

**고민사항**
1. 수정 시 어떤 단어를 쓸지 (modify라는 용어를 사용하는게 맞을지, 상태의 경우 update? change?)
2. 영양정보를 추가한다면 Menu내 MenuItemDetail VO내 Nutrition information VO 로 만들고 싶은데 이게 과연 좋은 방법일까요..?

(재영님 외 다른분들을 리뷰어로 넣은 이유는 그냥 더 많은 리뷰를 받고 싶어서 넣은거니 굳이 확인 안해주셔두 됩니다!~)

2024-03-11 05:52 UTC, SeungGun commented on menu/src/main/kotlin/org/heeheepresso/menu/common/BaseEntity.kt
> +@EntityListeners(AuditingEntityListener::class)
Auditing 리스너 등록하시면 애플리케이션 단에 Auditing 허용 어노테이션(`@EnableJpaAuditing`) 추가하셔야되는데 누락된 것 같습니다!

2024-03-11 05:53 UTC, SeungGun commented on menu/src/main/kotlin/org/heeheepresso/menu/domain/menu/model/Menu.kt
> +class Menu (
의도하신건지 모르겠지만 BaseEntity 상속도 누락된 것 같습니다.

2024-03-11 06:14 UTC, SeungGun commented
수정 네이밍같은 경우에 다른 레퍼런스 찾아봤었는데 레이어마다 이름이 다른 경우도 있긴하더라고요.
제 개인적인 생각인데, modify는 더 알맞게끔 바꾸는 느낌이고, change나 update는 새로운 값(상태)으로 갱신시켜준다라는 느낌이 듭니다.
그래서 엔티티 내의 메소드에서 필드를 변경하는 것은 개인적으로 change나 update가 어울릴 것 같다는 생각입니다. 

아래는 GPT한테 물어본 결과입니다. 

- Update(업데이트):
데이터나 정보를 최신으로 업데이트하는 것을 의미합니다.
주로 기존 데이터나 정보를 새로운 값으로 갱신하는 경우에 사용됩니다.
예를 들어, 데이터베이스의 레코드를 업데이트할 때 사용될 수 있습니다.
- Modify(수정):
변경된 부분이나 세부 사항을 수정하는 것을 의미합니다.
수정은 일반적으로 부분적인 변경을 가리킬 때 사용됩니다.
예를 들어, 객체의 특정 속성을 수정하거나 변경할 때 사용될 수 있습니다.
- Change(변경):
대상을 완전히 새로운 값이나 형태로 바꾸는 것을 의미합니다.
변경은 보다 광범위한 의미를 가지며, 완전히 새로운 상태로 대상을 변화시킬 때 사용됩니다.
예를 들어, 시스템의 설정을 변경하거나 사용자의 상태를 변경할 때 사용될 수 있습니다.

2024-03-11 11:54 UTC, kkkmj commented on menu/src/main/kotlin/org/heeheepresso/menu/common/BaseEntity.kt
> +@EntityListeners(AuditingEntityListener::class)
앗.... 오더팀꺼 몰래 훔쳐온건데 걸렸네요,,,,, 감사합니다

2024-03-11 12:25 UTC, jjh5887 commented
> 수정 네이밍같은 경우에 다른 레퍼런스 찾아봤었는데 레이어마다 이름이 다른 경우도 있긴하더라고요. 제 개인적인 생각인데, modify는 더 알맞게끔 바꾸는 느낌이고, change나 update는 새로운 값(상태)으로 갱신시켜준다라는 느낌이 듭니다. 그래서 엔티티 내의 메소드에서 필드를 변경하는 것은 개인적으로 change나 update가 어울릴 것 같다는 생각입니다.
> 
> 다른 분들도 네이밍 관련해서 의견있으면 주세요!
> 
> 아래는 GPT한테 물어본 결과입니다.
> 
> * Update(업데이트):
>   데이터나 정보를 최신으로 업데이트하는 것을 의미합니다.
>   주로 기존 데이터나 정보를 새로운 값으로 갱신하는 경우에 사용됩니다.
>   예를 들어, 데이터베이스의 레코드를 업데이트할 때 사용될 수 있습니다.
> * Modify(수정):
>   변경된 부분이나 세부 사항을 수정하는 것을 의미합니다.
>   수정은 일반적으로 부분적인 변경을 가리킬 때 사용됩니다.
>   예를 들어, 객체의 특정 속성을 수정하거나 변경할 때 사용될 수 있습니다.
> * Change(변경):
>   대상을 완전히 새로운 값이나 형태로 바꾸는 것을 의미합니다.
>   변경은 보다 광범위한 의미를 가지며, 완전히 새로운 상태로 대상을 변화시킬 때 사용됩니다.
>   예를 들어, 시스템의 설정을 변경하거나 사용자의 상태를 변경할 때 사용될 수 있습니다.

저도 modify 1표!
BaseEntity에 modifiedBy 로 컬럼 설정하셨으니 modify로 하시는게 좋아보입니다.

2024-03-11 12:34 UTC, jjh5887 commented on menu/src/main/kotlin/org/heeheepresso/menu/domain/menu/model/Category.kt
> +    COFFEE("COFFEE"),
요거 desc 추가하신거면 살짝 설명을 위한 프로퍼티인거 같은데
ENUM 명 그래도 쓰는 것보단 해당 ENUM에 대한 설명이나 한글명을 쓰시는게 어떨까요??

2024-03-11 12:34 UTC, jjh5887 commented on menu/src/main/kotlin/org/heeheepresso/menu/domain/menu/repository/MenuRepository.kt
> +interface MenuRepository : CrudRepository<Menu, Long> {
이거 JpaRepositry 안쓰고 CurdRepositroy 쓰신 이유가 궁금합니다.

2024-03-11 12:34 UTC, jjh5887 commented on menu/src/main/kotlin/org/heeheepresso/menu/domain/menu/service/MenuService.kt
> +    fun modifyStatus(id: Long, request: ModifyStatusRequest): Menu{
이거 @Transactional 없이도 잘 작동 하나요??

2024-03-11 12:34 UTC, jjh5887 commented on menu/src/test/kotlin/org/heeheepresso/menu/domain/menu/service/MenuServiceTests.kt
> +                val result = menuService.modifyStatus(3L, request)
이거 modify 메소드가 해당 메소느 내부에서 수정한 객체 자체를 반환해주는데
디비에 실제로 수정이 되었는지 테스트 하시려면 별도로 조회해서 하시는게 좋지 않을까요?

2024-03-11 13:29 UTC, HeeJaeKK commented on menu/src/main/kotlin/org/heeheepresso/menu/common/BaseEntity.kt
> +@EntityListeners(AuditingEntityListener::class)
검거완료

2024-03-11 13:30 UTC, HeeJaeKK approved these changes

2024-03-14 02:31 UTC, yoon-chaejin requested changes
Comment 달린 부분 참고해서 수정해주세요~
늦은 리뷰 죄송합니다..

2024-03-14 02:31 UTC, yoon-chaejin commented on menu/src/main/kotlin/org/heeheepresso/menu/domain/menu/model/Menu.kt
> +    var flagType: FlagType? = null,
추후 해당 값에 대한 null 체크 등을 별도로 하기보다는 NONE 또는 GENERAL 과 같은 값을 정의해서 사용하는 건 어떨까요...?

2024-03-14 02:31 UTC, yoon-chaejin commented on menu/src/main/kotlin/org/heeheepresso/menu/domain/menu/model/Category.kt
> +    COFFEE("COFFEE"),
권호님 의견에 추가해서, 카테고리에 대한 desc 가 실제 사용되는 게 아니라면 제거하는 것도 의견 드립니다.

2024-03-14 02:32 UTC, yoon-chaejin commented on menu/src/main/kotlin/org/heeheepresso/menu/domain/menu/repository/MenuRepository.kt
> +interface MenuRepository : CrudRepository<Menu, Long> {
@jjh5887 
이 내용은 제가 답변 드리면, Kotlin이랑 JPA에 대해 모르는 부분이 많아서 점진적으로 추가해나가고 있습니다.

상세한 히스토리는 다음과 같습니다.
Kotlin + Spring Data JPA 사용을 위해 [추가 설정이 필요한 부분](https://colabear754.tistory.com/145)이 있다고 확인했는데, Kotlin 과 JPA 에 대해 모르는 부분들이 많이 있어서 우선 [Kotlin 가이드](https://kotlinlang.org/docs/jvm-spring-boot-using-crudrepository.html)에 명시된 Spring Data JDBC 의 CrudRepository 로 시작했고, Entity 에 따라 테이블을 생성해주는 기능은 활용하기 위해 라이브러리를 spring-data-jdbc 에서 spring-data-jpa 로 변경해서 사용하고 있는 상태입니다. 추후 메뉴 쪽에 옵션 등의 엔티티 추가 시에 필요하다면 jpa 의 다른 기능도 활용할 예정이긴 합니다!

2024-03-17 09:18 UTC, kkkmj commented on menu/src/main/kotlin/org/heeheepresso/menu/domain/menu/model/Category.kt
> +    COFFEE("COFFEE"),
일단 ENUM에서 &표시가 안돼서 프론트에게 줄때 편하려고 만든건데
할거면 desc라고  했으면 안됐긴했겠네요,,

2024-03-17 09:19 UTC, kkkmj commented on menu/src/test/kotlin/org/heeheepresso/menu/domain/menu/service/MenuServiceTests.kt
> +                val result = menuService.modifyStatus(3L, request)
네네 그러게요 바꿔서 하겠습니다 감사합니다~

2024-04-02 12:00 UTC, merged