[GW] feat: 홈 화면 API 프레임 구현 및 리팩토링
HeeHeePresso/Backend pull request #54
Opened 2024-04-08 08:41 UTC by SeungGun

## Related Issue
close #48 

- 다른 서비스와의 통신이 아니라 홈 화면 데이터 제공하는 내부 흐름에 포커싱을 맞춰서 다른 분들 말고 희재님만 코드 리뷰어로 등록했습니다.
- 다른 서비스와의 통신에 대한 연동 및 테스트 작업은 이 이후에 할 예정입니다.
- 그래도 코드 퀄리티에 대한 리뷰는 언제나 환영입니다. 

## 변경 사항

### 홈 화면 API
- 피그마 상에서는 '시즌 특별 메뉴'와 같은 타이틀로 해당 추천 매뉴 목록을 받아오기 때문에 때에 따라 타이틀로 추천 메뉴를 가져올 수 있게 RequestParam으로 타이틀을 받게했습니다. 
- 이 타이틀을 추천 서비스의 핸들러로써 사용하게끔 했습니다.
- 하지만 여기에 더해서 홈 화면에 타이틀에 대한 메뉴가 반드시 하나라는 보장은 없을 수 있으므로 타이틀을 리스트 형태로 받아서 결과 자체도 각각 타이틀에 대한 추천 메뉴 목록을 반환하게끔 설계해봤습니다. 
- 임의로 이벤트 서비스를 만들고 임시 이미지만 반환하게끔 했습니다. 
- 최종적으로 해당 각 타이틀에 대한 메뉴 목록들과 이벤트 피쳐 목록을 최종 결과로 반환합니다.

### 리팩토링
- 우선 기존 코드에서 RecommendedMenu와 MenuDetail의 역할은 다르지만 필드가 똑같았기에 중복된다고 판단되었습니다. 
  - 추가로 현재까지 구현한 API에 대해서는 MenuDetail 표현은 아닌 것 같다고 생각되어서(Detail은 상세 메뉴 페이지에서 요구하는 데이터라고 생각함) MenuInfo와 같은 네이밍으로 수정했습니다.
- 그래서 추천 서비스로부터의 결과를 얻는 것은 추천 메뉴의 ID 목록들만 받아오게 하고, 실제 메뉴 목록에서 필요한 데이터는 메뉴 서비스로부터 얻게끔 수정했습니다.
- 여기에 MoreInfo 인터페이스가 사용되는 것으로 추측되어지는데, List로 하신 의도를 생각해봐도 '메뉴 정보'에 대해 추가적인 정보를 입힐 수 있는 다른 부분이 있는지 잘 떠오르지 않았습니다. 
- 그래서 기존 MoreInfo 구현체인 MenuDetailInfo를 수정했는데
  1. 추천 서비스로부터 받은 메뉴 ID 목록들을 input으로
  2. 결과인 '메뉴 정보' 목록들에게 메뉴 조회 서비스로부터 해당 결과를 매핑해주었습니다. 
- 그리고 홈 화면의 최종 결과로는 MenuInfo가 아닌 새롭게 정의한 MenuBase에 들어있는 필드를 전달하게끔 했는데, 해당 화면에 fit한 데이터를 전달하기 위해 새롭게 정의했습니다. 
  - 그래서 MenuInfo와 MenuBase가 상속관계가 될 수 있을 거 같아서 처음에 정의해봤다가 이 두 클래스 모두 data class였는데  data class는 웬만하면 상속을 사용하지 말라는 글을 보긴 했습니다. 아직 코틀린에 익숙하지 않아서 그런 것이니 좋은 방법 있으면 코멘트 부탁드립니다. 
- 그리고 Context의 경우 해당 객체를 가져오는 책임을 누가 가져야하는지를 생각해봐도 아직은 답이 안나와서, 우선 MenuCategoryService에 종속시켜놓았습니다. 
  - 메뉴 관련 조회할 때 공통적으로 Context가 필요할 것 같아서 public으로 바꿨습니다.

### 멀티 모듈 등록
- 등록 안된 나머지 서비스들 모두 멀티 모듈에 등록해놨습니다.

---

- 리팩토링하다보니 너무 어지러워서 제가 짜치는 코드를 써놨을 것 같아서 일단 PR 올려놓고 수정해보려고 합니다.

2024-04-08 11:10 UTC, HeeJaeKK commented on gateway/src/main/kotlin/org/heeheepresso/gateway/event/EventService.kt
> +        return ImmutableList.of(
왜 같은 사진이 3장입니까?

2024-04-08 11:25 UTC, HeeJaeKK requested changes
부탁드릴게요

2024-04-08 11:30 UTC, SeungGun commented on gateway/src/main/kotlin/org/heeheepresso/gateway/event/EventService.kt
> +        return ImmutableList.of(
임시 처리..입니다..^^

2024-04-09 06:09 UTC, SeungGun commented on gateway/src/main/kotlin/org/heeheepresso/gateway/recommendation/RecommendationService.kt
> +                handler = request.handler ?: "SEASON_RECOMMENDED"
겉으로는 짜치지만 아직 추천 서비스랑 통신하지 않아서 임시 방편으로 해놨씁니다...
핸들러가 null일때는 추천팀에서 알아서 제공해주는 역할로 하기 위해 했습니다.

2024-04-09 06:09 UTC, SeungGun commented on gateway/src/main/kotlin/org/heeheepresso/gateway/home/HomeController.kt
> +    ): HomePageResponse {
반영했습니당

2024-04-09 06:12 UTC, SeungGun commented
> 부탁드릴게요

아직 통신까지 하지 않은 상태에서 요청하신 사항 수정 해봤습니다.

Context에 MoreInfo가 필요없다고 판단되서 지웠고, 각 서비스에서 MoreInfo가 필요한 경우에 해당 서비스가 DI받아서 사용하게끔 했습니다.
그에 따라 MoreInfo는 가져온 메뉴 정보(Primary Key)에 추가 정보를 덧붙이는 역할로 사용했습니다. 

그리고 홈 화면 같이 특정 타이틀에 의해 추천 메뉴를 받는 것이 아니라 추천 서비스로부터 컨텐츠 제공을 위해 핸들러를 nullable하게 바꿨습니다. 
요청은 nullable하게, 응답은 not nullable하게 했습니다.

2024-04-10 08:50 UTC, SeungGun commented
> > 부탁드릴게요
> 
> 아직 통신까지 하지 않은 상태에서 요청하신 사항 수정 해봤습니다.
> 
> Context에 MoreInfo가 필요없다고 판단되서 지웠고, 각 서비스에서 MoreInfo가 필요한 경우에 해당 서비스가 DI받아서 사용하게끔 했습니다. 그에 따라 MoreInfo는 가져온 메뉴 정보(Primary Key)에 추가 정보를 덧붙이는 역할로 사용했습니다.
> 
> 그리고 홈 화면 같이 특정 타이틀에 의해 추천 메뉴를 받는 것이 아니라 추천 서비스로부터 컨텐츠 제공을 위해 핸들러를 nullable하게 바꿨습니다. 요청은 nullable하게, 응답은 not nullable하게 했습니다.

다시 수정했습니다. 성윤님이랑 회의를 하면서 인사이트를 얻었는데,
핸들러가 null인 경우에는 어떤 데이터를 요구하고 받아야하는지 모호해졌기 때문에 홈 화면 API에 대한 핸들러를 정의해서 요청하는 것으로 변경했습니다.
그에 따라 기존 handler를 nullable처리한 것을 다시 not null 처리하였습니다. 

그리고 피그마 상에서는 응답에 대해 어떤 메뉴인가 에 대한 용어를 'title'을 사용하였는데, 메뉴 이름과 용어 혼동으로 인해 게이트웨이에서 전달할 용어를 handler로 통일하였습니다.

2024-04-10 08:51 UTC, SeungGun commented on gateway/src/main/kotlin/org/heeheepresso/gateway/recommendation/RecommendationService.kt
> +                handler = if (request.handler == "HOME") "SEASON_RECOMMENDED" else request.handler
요것도 임시방편입니다.

2024-04-12 16:21 UTC, HeeJaeKK approved these changes

2024-04-13 10:05 UTC, merged